baseURL = 'https://www.elesscode.com'
languageCode = 'en-us'
title = 'elesscode'
theme = "ananke"
publishdir = 'docs'
[params]
  body_classes = "bg-light-yellow font-fira"
  post_content_classes = "font-fira"
  custom_css = ["custom.css","special.css"]
  show_reading_time = true
